name: kora-labs-common
on:
  push:
    branches:
      - master
  workflow_dispatch:
permissions:
  id-token: write  # Required for OIDC
  contents: read
  packages: write  # Required for GitHub Packages publish
jobs:
  deploy:
    name: Deploying from ${{ github.ref_name }}
    environment: mainnet
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 24
        registry-url: https://registry.npmjs.org

    - name: Install
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Test
      run: npm run test

    - name: Build
      run: npm run build && cp package.json ./lib/package.json

    - name: Publish to GitHub Packages
      run: |
        npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
        cd ./lib && npm publish --@koralabs:registry='https://npm.pkg.github.com' || echo "GitHub Packages version may already exist"

    - name: Publish to npmjs
      run: cd ./lib && npm publish --provenance --access public || echo "npmjs version may already exist"
